version: '3.7'

networks:
  default:

services:
  cqrs-app:
    container_name: cqrs-app
    image: cqrs-app-dev:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - "./:/usr/app"
    networks:
      - default

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - default
  
  mongodb-manager:
    container_name: mongodb-manager
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    image: mongo-express
    networks:
      - default

  gtasks:
    container_name: gtasks
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    restart: always
    command: -host 0.0.0.0 -port 8123 
      -queue "projects/dev/locations/local/queues/create-example"
    ports:
    - "${TASKS_PORT:-8123}:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://cqrs-app:3000
    networks:
      - default