version: '3.7'

networks:
  default:

services:
  cqrs-app:
    container_name: cqrs-app
    image: cqrs-app-dev:latest
    restart: always
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - "./:/usr/app"
    networks:
      - default
    environment:
      GCP_QUEUE_HOST: gtasks
      GCP_QUEUE_PORT: 8123
      GCP_QUEUE_PROJECT: dev
      GCP_QUEUE_REGION: local
      GCP_QUEUE_HANDLER_URL: http://cqrs-app:3000/api/v1/queue-handler
      MONGODB_CONNECTION: mongodb://mongodb:27017
      MONGODB_DATABASE: App

  # mongodb:
  #   container_name: mongodb
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin
  #   networks:
  #     - default

  gtasks:
    container_name: gtasks
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    restart: always
    command: -host 0.0.0.0 -port 8123 
      -queue "projects/dev/locations/local/queues/create-example"
    ports:
    - "${TASKS_PORT:-8123}:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://cqrs-app:3000
    networks:
      - default