name: CI-CD Pipeline

on:
  push:
    paths-ignore:
      - "**/README.md"
      - "docs/**"
      - "env/**"
      - "scripts/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: node:16.14.2
    env:
      NODE_ENV: ci
    steps:
      - run: env
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Run lint
        run: |
          yarn lint

  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    environment: test
    container:
      image: node:16.14.2
      options: --name cqrs-app
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
      tasks-queue:
        image: mathulbrich/cqrs-cloud-tasks-emulator:latest
        ports:
          - 8123:8123
    steps:
      - run: env
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install NPM dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run Tests
        env:
          APP_NAME: cqrs-app
          APP_PORT: 3000
          GCP_QUEUE_HOST: tasks-queue
          GCP_QUEUE_PORT: 8123
          GCP_QUEUE_PROJECT: dev
          GCP_QUEUE_REGION: local
          GCP_QUEUE_HANDLER_HOST: cqrs-app
          GCP_QUEUE_HANDLER_PORT: 3000
          GCP_QUEUE_HANDLER_ENDPOINT: api/v1/queue-handler
          MONGODB_CONNECTION_URI: mongodb://admin:admin@mongodb/app?authSource=admin # will be ignored on integration testing
          NODE_ENV: ci
        run: |
          yarn test:cov
      - name: Store test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
          retention-days: 1
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v3
