name: CI-CD Pipeline

on:
  push:
    paths-ignore:
      - "**/README.md"
      - "docs/**"
      - "env/**"
      - "scripts/**"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: node:16.14.2
    env:
      NODE_ENV: ci
    steps:
      - run: env
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Run lint
        run: |
          yarn lint

  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    environment: test
    container:
      image: node:16.14.2
      options: --name cqrs-app
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
      sqs:
        image: softwaremill/elasticmq-native
        ports:
          - 9324:9324
    steps:
      - run: env
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install NPM dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run Tests
        env:
          APP_NAME: cqrs-app
          APP_PORT: 3000
          AWS_ACCESS_KEY_ID: cqrsappaccesskeyid
          AWS_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: cqrsappsecretaccesskey
          MONGODB_CONNECTION_URI: mongodb://admin:admin@mongodb/app?authSource=admin # will be ignored on integration testing
          NODE_ENV: ci
          SQS_QUEUE_BASE_URL: http://sqs:9324/queue/
          SQS_QUEUE_ENDPOINT: http://sqs:9324
          SQS_QUEUE_SUFFIX: .fifo
        run: |
          yarn test:cov
      - name: Store test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
          retention-days: 1
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v3
