name: CI-CD Pipeline

on:
  push:
    paths-ignore:
      - "**/README.md"
      - "docs/**"
      - "env/**"
      - "scripts/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:16-slim
    env:
      NODE_ENV: ci
    steps:
      - run: env
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install NPM dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build:prod

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: node:16-slim
    env:
      NODE_ENV: ci
    steps:
      - run: env
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install NPM dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint

  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    environment: test
    container:
      image: node:16-slim
      options: --name cqrs-app
    services:
      dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
          - 8000:8000
      sqs:
        image: softwaremill/elasticmq-native
        ports:
          - 9324:9324
      s3:
        image: fclairamb/minio-github-actions
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: cqrsappaccesskeyid
          MINIO_SECRET_KEY: cqrsappsecretaccesskey
    steps:
      - run: env
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install NPM dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        env:
          APP_NAME: cqrs-app
          APP_PORT: 3000
          AWS_ACCESS_KEY_ID: cqrsappaccesskeyid
          AWS_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: cqrsappsecretaccesskey
          DYNAMO_DB_ENDPOINT: http://dynamodb:8000
          NODE_ENV: ci
          S3_STORAGE_ENDPOINT: http://s3:9000
          SQS_QUEUE_BASE_URL: http://sqs:9324/queue/
          SQS_QUEUE_ENDPOINT: http://sqs:9324
          SQS_QUEUE_SUFFIX: .fifo
        run: |
          yarn test:cov
      - name: Store test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/
          retention-days: 1
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/master'
        uses: codecov/codecov-action@v3
